feat: update maintainer scripts for user systemd service
Backport some debhelper-compat 14 features of dh_installsystemduser for:

1. Start and stop user level systemd;
2. Run daemon-reload after package is removed.

The shell scripts is almost the same as the arguments passed to `system`
function in deb-systemd-invoke.

Signed-off-by: black-desk <me@black-desk.cn>

diff --git a/debian/linglong-bin.postinst b/debian/linglong-bin.postinst
--- a/debian/linglong-bin.postinst
+++ b/debian/linglong-bin.postinst
@@ -4,84 +4,33 @@
 #
 # SPDX-License-Identifier: LGPL-3.0-or-later
 
-# This systemd config is automatically generated from dh_installsysusers/13.11.4.
-# When the dh-compat < 13, some of them will not be generated.
-# So we just make this hard code.
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} linglong.conf
-fi
+#DEBHELPER#
 
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-        if [ -z "${DPKG_ROOT:-}" ] ; then
-                # The following line should be removed in trixie or trixie+1
-                deb-systemd-helper --user unmask 'linglong-upgrade.service' >/dev/null || true
+# NOTE:
+# Backport dh_installsystemduser features here to (re)start user level services here.
+# This is needed until debhelper-compat 14.
+instances="$(systemctl --no-legend --quiet list-units 'user@*' | sed -n -r 's/.*user@([0-9]+).service.*/\1/p')"
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
+        if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
+                # Here we reload synchronously, as we really need to block in
+                # order to ensure the following restart also works. Furthermore,
+                # if there is no D-Bus user session, the restart won't work either,
+                # so there's no point if falling back to signals - so either both
+                # of these operations work, or both fail.
 
-                # was-enabled defaults to true, so new installations run enable.
-                if deb-systemd-helper --quiet --user was-enabled 'linglong-upgrade.service' ; then
-                        # Enables the unit on first installation, creates new
-                        # symlinks on upgrades if the unit file has changed.
-                        deb-systemd-helper --user enable 'linglong-upgrade.service' >/dev/null || true
-                else
-                        # Update the statefile to add new symlinks (if any), which need to be
-                        # cleaned up on purge. Also remove old symlinks.
-                        deb-systemd-helper --user update-state 'linglong-upgrade.service' >/dev/null || true
-                fi
+                # NOTE:
+                # orgin script from postinst-systemd-user-restart
+                # deb-systemd-invoke --user daemon-reload >/dev/null || true
+                # deb-systemd-invoke --user restart #UNITFILES# >/dev/null || true
 
-                deb-systemd-helper --user unmask 'linglong-session-helper.service' >/dev/null || true
-                if deb-systemd-helper --quiet --user was-enabled 'linglong-session-helper.service' ; then
-                        deb-systemd-helper --user enable 'linglong-session-helper.service' >/dev/null || true
-                else
-                        deb-systemd-helper --user update-state 'linglong-session-helper.service' >/dev/null || true
-                fi
+                for instance in $instances; do
+                        systemctl --user --machine="$instance"@ daemon-reload >/dev/null || true
+                done
+                for instance in $instances; do
+                        systemctl --user --machine="$instance"@ restart linglong-session-helper.service >/dev/null || true
+                done
         fi
 fi
-
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-        if [ -z "${DPKG_ROOT:-}" ] ; then
-                # The following line should be removed in trixie or trixie+1
-                deb-systemd-helper --user unmask 'linglong-upgrade.timer' >/dev/null || true
-
-                # was-enabled defaults to true, so new installations run enable.
-                if deb-systemd-helper --quiet --user was-enabled 'linglong-upgrade.timer' ; then
-                        # Enables the unit on first installation, creates new
-                        # symlinks on upgrades if the unit file has changed.
-                        deb-systemd-helper --user enable 'linglong-upgrade.timer' >/dev/null || true
-                else
-                        # Update the statefile to add new symlinks (if any), which need to be
-                        # cleaned up on purge. Also remove old symlinks.
-                        deb-systemd-helper --user update-state 'linglong-upgrade.timer' >/dev/null || true
-                fi
-        fi
-fi
-
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-        # The following line should be removed in trixie or trixie+1
-        deb-systemd-helper unmask 'org.deepin.linglong.PackageManager.service' >/dev/null || true
-
-        # was-enabled defaults to true, so new installations run enable.
-        if deb-systemd-helper --quiet was-enabled 'org.deepin.linglong.PackageManager.service'; then
-                # Enables the unit on first installation, creates new
-                # symlinks on upgrades if the unit file has changed.
-                deb-systemd-helper enable 'org.deepin.linglong.PackageManager.service' >/dev/null || true
-        else
-                # Update the statefile to add new symlinks (if any), which need to be
-                # cleaned up on purge. Also remove old symlinks.
-                deb-systemd-helper update-state 'org.deepin.linglong.PackageManager.service' >/dev/null || true
-        fi
-fi
-
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-        if [ -d /run/systemd/system ]; then
-                systemctl --system daemon-reload >/dev/null || true
-                if [ -n "$2" ]; then
-                        _dh_action=restart
-                else
-                        _dh_action=start
-                fi
-                deb-systemd-invoke $_dh_action 'org.deepin.linglong.PackageManager.service' >/dev/null || true
-        fi
-fi
-# End automatically added section
 
 case "$1" in
 configure)
@@ -89,7 +38,7 @@ configure)
         shift
         # enable kernel.unprivileged_userns_clone
         # disable kernel.apparmor_restrict_unprivileged_unconfined and kernel.apparmor_restrict_unprivileged_userns
-        if [ -f /usr/lib/sysctl.d/linglong.conf ];then
+        if [ -f /usr/lib/sysctl.d/linglong.conf ]; then
                 sysctl -p /usr/lib/sysctl.d/linglong.conf
         fi
         ;;
